# Generated by Django 5.2.3 on 2025-07-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('xml', 'XML')], default='json', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_configurations', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=255)),
                ('attribute', models.CharField(default='text', max_length=50)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='accounts.scrapingconfiguration')),
            ],
        ),
    ]
